Some common terms to remember:
<br>
1. Corpus: The entire body of text
2. Vocabulary
3. Document
4. word

# Bag of Words

In [21]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer # for bags of words
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
df = pd.DataFrame({"text":["People watch dswithbappy", "dswithbappy watch dswithbappy", "people write comment", "dswithbappy write comment"], "output":[1,1,0,0]})
df

text  output
0       People watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [5]:
# Creating an instance of BOW
cv = CountVectorizer() 


In [6]:
# Creating the vector space i.e numerical representation for the text column
bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [8]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]], dtype=int64)

In [10]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]], dtype=int64)

In [11]:
X = bow.toarray()
y = df['output']

In [12]:
# Bi gram - two words consider as token
cv = CountVectorizer(ngram_range=(2,2))

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [17]:
# Ti gram
cv = CountVectorizer(ngram_range=(3,3))

In [18]:
bow = cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


In [20]:
print(bow.toarray())

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]


TF-IDF( Term Frequency - Inverse Document Frequency)

In [22]:
# create instance of tfid
tfid = TfidfVectorizer()
arr = tfid.fit_transform(df['text']).toarray()

In [23]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [24]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]


In [25]:
cv.get_feature_names_out()

array(['dswithbappy watch dswithbappy', 'dswithbappy write comment',
       'people watch dswithbappy', 'people write comment'], dtype=object)